# .github/actions/setup-environments/action.yml
name: 'Setup Environments'
description: 'Sets up Node.js, Ruby, and Java environments'

inputs:
  event_name:
    description: 'The name of the event that triggered the workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # - name: Set environment name
    #   shell: bash
    #   run: |
    #     if [[ "${{ inputs.event_name }}" == "published"]]; then
    #       echo "ENVIRONMENT_NAME=Production" >> $GITHUB_ENV
    #     else
    #       echo "ENVIRONMENT_NAME=Staging" >> $GITHUB_ENV
    #     fi
