# .github/actions/setup-environments/action.yml
name: 'Setup Environments'
description: 'Sets up Node.js, Ruby, and Java environments'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set environment name
      shell: bash
      run: |
        if [[ "${{ inputs.eventName }}" == "push" && "${{ inputs.ref }}" == "refs/heads/main" ]]; then
          echo "ENVIRONMENT_NAME=Staging" >> $GITHUB_ENV
        elif [[ "${{ inputs.eventName }}" == "workflow_dispatch" ]]; then
          echo "ENVIRONMENT_NAME=${{ inputs.environmentName }}" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT_NAME=Production" >> $GITHUB_ENV
        fi
