# .github/actions/setup-environments/action.yml
name: 'Setup Environments'
description: 'Sets up Node.js, Ruby, and Java environments'

inputs:
  eventName:
    description: 'The name of the event that triggered the workflow'
    required: true
  ref:
    description: 'The branch or tag ref that triggered the workflow'
    required: true
  environment:
    description: 'The environment name from workflow dispatch'
    required: false
    default: 'Production'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Set environment name
      shell: bash
      run: |
        if [[ "${{ inputs.eventName }}" == "push" && "${{ inputs.ref }}" == "refs/heads/main" ]]; then
          echo "ENVIRONMENT_NAME=Staging" >> $GITHUB_ENV
        elif [[ "${{ inputs.eventName }}" == "workflow_dispatch" ]]; then
          echo "ENVIRONMENT_NAME=${{ inputs.environment }}" >> $GITHUB_ENV
        fi
