name: Checkout Code
on:
  workflow_call:

jobs:
  test-setup-env:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Add Java 17 to system ENV
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: yarn install

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
