name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build the application for"
        type: environment
        required: true
  push:
    branches:
      - main
  release:
    types: [published]

env:
  ENVIRONMENT_NAME: ${{ github.event_name == 'release' && 'Production' || inputs.environment || 'Staging' }}

jobs:
  build:
    environment: ${{ github.event_name == 'release' && 'Production' || inputs.environment || 'Staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the custom action to set up Node.js, Ruby, and Java
      - name: Setup Environments
        uses: ./.github/actions/setup-environment
        with:
          event_name: ${{ github.event_name }}
      - name: Print environment name
        run: echo "The environment name is $ENVIRONMENT_NAME"

      # Additional steps specific to this job
      - name: Install dependencies
        run: yarn install

      - name: Start the app
        run: yarn start
