name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build the application for"
        type: environment
        required: true
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    environment: ${{ github.event.action == 'published' && 'Production' || 'Staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the custom action to set up Node.js, Ruby, and Java
      - name: Setup Environments
        uses: ./.github/actions/setup-environment
        with:
          eventName: ${{ github.event_name }}
          ref: ${{ github.ref }}
          environment: ${{ github.event.inputs.environment }}

      - name: Print environment name
        run: echo "The environment name is $ENVIRONMENT_NAME"

      # Additional steps specific to this job
      - name: Install dependencies
        run: yarn install

      - name: Start the app
        run: yarn start
