name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build the application for"
        type: environment
        required: true
  push:
    branches:
      - main
  release:
    types: [published]

env:
  ENVIRONMENT_NAME: ${{ github.event_name == 'release' && 'Production' || inputs.environment || 'Staging' }}

jobs:
  build:
    environment: ${{ github.event_name == 'release' && 'Production' || inputs.environment || 'Staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSL directory and symbolic link
        run: |
          sudo wget -O /usr/lib/ssl/cert.pem "https://curl.haxx.se/ca/cacert.pem"

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
          bundler-cache: true

      - name: Run ruby script
        env:
          SLACK_MOBILE_BOT_TOKEN: ${{ secrets.SLACK_MOBILE_BOT_TOKEN }}
        run: |
          bundle exec fastlane run slack_message
      # Use the custom action to set up Node.js, Ruby, and Java
      # - name: Setup Environments
      #   uses: ./.github/actions/setup-environment
      #   with:
      #     event_name: ${{ github.event_name }}

      # - name: Print environment name
      #   run: |
      #     echo "The environment name is $ENVIRONMENT_NAME"
